"""Export the mesh directly from a ``.re2`` file, with no solution data.

Useful for checking a boundary-condition setup *before* (or without) running a
case.  Writes one named multiblock ``<case>_re2_mesh.vtm`` built from the linear
element geometry stored in the ``.re2`` (the ``.re2`` has no GLL nodes — those
are generated by the solver — so this mesh is straight-edged):

* a ``volume`` block — the full linear hexahedral mesh (cell array ``elementID``);
* a ``boundaries`` group of named blocks (inlet, wall, ...) — one per mesher
  sideset when the ``.re2`` has numeric sidesets (gmsh2nek/exo2nek/cgns2nek),
  otherwise per connectivity+normal auto-split (genbox).  Each block also keeps
  a ``sidesetID`` cell array.

ParaView shows the block names directly, so no thresholding is needed.  This
path is serial and needs only pymech + pyvista.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List

import numpy as np

from . import geometry, nekfaces
from .re2boundary import INTERIOR_CODES, _face_label, read_re2_header
from .regions import region_infos, split_faces

# Corner (ix, jy, kz) order for a VTK_HEXAHEDRON (indices into a 2x2x2 element).
_VTK_HEX = [
    (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
    (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1),
]


@dataclass
class Re2Mesh:
    element_corners: np.ndarray  # (nel, 8, 3) VTK-hex-ordered corners
    bface_corners: np.ndarray    # (Nf, 4, 3)
    bface_sideset: np.ndarray    # (Nf,) int sideset id (0 if none)
    bface_label: np.ndarray      # (Nf,) str label (code or bc<id>)
    bface_normal: np.ndarray     # (Nf, 3) outward unit normals
    nelgt: int
    nelgv: int
    ndim: int

    @property
    def is_cht(self) -> bool:
        return self.nelgv < self.nelgt


def read_re2_mesh(path: str | Path) -> Re2Mesh:
    """Read element geometry and boundary faces from a ``.re2`` (one pass)."""
    from pymech.neksuite import readre2

    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"re2 file not found: {path}")

    nelgt_hdr, _, nelgv_hdr = read_re2_header(path)
    mesh = readre2(str(path))
    ndim = int(mesh.ndim)
    nel = int(mesh.nel)
    nf_per_elem = nekfaces.n_faces(ndim)

    elem_corners = np.zeros((nel, 8, 3))
    corners_list: List[np.ndarray] = []
    ecen_list: List[np.ndarray] = []
    sideset_list: List[int] = []
    label_list: List[str] = []

    for e in range(nel):
        el = mesh.elem[e]
        pos = np.asarray(el.pos)  # (ndim, lz, ly, lx), lx=2
        lz, ly, lx = pos.shape[1], pos.shape[2], pos.shape[3]

        for k, (ix, jy, kz) in enumerate(_VTK_HEX):
            for d in range(ndim):
                elem_corners[e, k, d] = pos[d, kz, jy, ix]

        ec = np.array([pos[d].mean() if d < ndim else 0.0 for d in range(3)])
        bcs = el.bcs[0]
        for f0 in range(nf_per_elem):
            code = str(bcs[f0][0]).strip()
            if code in INTERIOR_CODES:
                continue
            boundary_id = int(round(float(bcs[f0][7])))
            face = f0 + 1
            idx = nekfaces.face_corner_indices(face, lx, ly, lz)
            corner = np.zeros((4, 3))
            for m, (kz, jy, ix) in enumerate(idx):
                for d in range(ndim):
                    corner[m, d] = pos[d, kz, jy, ix]
            corners_list.append(corner)
            ecen_list.append(ec)
            sideset_list.append(boundary_id)
            label_list.append(_face_label(code, boundary_id))

    nf = len(label_list)
    if nf:
        bcorners = np.asarray(corners_list, dtype=np.float64)
        ecen = np.asarray(ecen_list, dtype=np.float64)
        bnormal = geometry.outward_normals(bcorners, ecen)
    else:
        bcorners = np.zeros((0, 4, 3))
        bnormal = np.zeros((0, 3))

    return Re2Mesh(
        element_corners=elem_corners,
        bface_corners=bcorners,
        bface_sideset=np.asarray(sideset_list, dtype=np.int64),
        bface_label=np.asarray(label_list, dtype="<U8"),
        bface_normal=bnormal,
        nelgt=nel,
        nelgv=int(nelgv_hdr),
        ndim=ndim,
    )


def _dedup(points: np.ndarray, decimals: int = 9):
    """Return (unique_points, inverse_index) merging coincident points."""
    key = np.round(points, decimals)
    _, first, inverse = np.unique(key, axis=0, return_index=True,
                                  return_inverse=True)
    return points[first], inverse.ravel()


def _boundary_polydata(mesh: Re2Mesh, mask: np.ndarray):
    """Build a PolyData of the boundary faces selected by ``mask``."""
    import pyvista as pv

    corners = mesh.bface_corners[mask]
    nf = corners.shape[0]
    upts, inv = _dedup(corners.reshape(-1, 3))
    quads = inv.reshape(nf, 4)
    faces = np.hstack([np.full((nf, 1), 4, dtype=np.int64), quads]).ravel()
    poly = pv.PolyData(upts, faces)
    poly.cell_data["sidesetID"] = mesh.bface_sideset[mask]
    return poly


def _volume_grid(mesh: Re2Mesh):
    """Build the linear hexahedral volume UnstructuredGrid."""
    import pyvista as pv

    nel = mesh.element_corners.shape[0]
    upts, inv = _dedup(mesh.element_corners.reshape(-1, 3))
    conn = inv.reshape(nel, 8)
    cells = np.hstack([np.full((nel, 1), 8, dtype=np.int64), conn]).ravel()
    celltypes = np.full(nel, pv.CellType.HEXAHEDRON, dtype=np.uint8)
    grid = pv.UnstructuredGrid(cells, celltypes, upts)
    grid.cell_data["elementID"] = np.arange(nel, dtype=np.int64)
    return grid


def _boundary_groups(mesh: Re2Mesh, normal_angle_deg: float):
    """Return (group_id array, infos, kind).

    Groups boundary faces by the mesher ``sidesetID`` when the mesh has numeric
    sidesets (gmsh2nek/exo2nek/cgns2nek); otherwise by the geometric auto-split
    (genbox).  ``infos`` are RegionInfo summaries keyed by the returned group id.
    """
    has_sidesets = bool((mesh.bface_sideset > 0).any())
    if has_sidesets:
        uniq = np.unique(mesh.bface_sideset)
        remap = {s: i for i, s in enumerate(uniq.tolist())}
        group = np.array([remap[s] for s in mesh.bface_sideset.tolist()],
                         dtype=np.int64)
        kind = "sidesetID"
    else:
        group = split_faces(mesh.bface_corners, mesh.bface_normal,
                            normal_angle_deg)
        kind = "region"
    infos = region_infos(mesh.bface_corners, mesh.bface_normal, group,
                         codes=mesh.bface_label)
    return group, infos, kind


def export_mesh(re2file: Path, outdir: Path, casename: str,
                normal_angle_deg: float = 40.0, write_volume: bool = True,
                interactive: bool = False, reconfigure: bool = False):
    """Read a ``.re2`` and write a named multiblock ``.vtm`` (volume + named
    boundary surfaces), all from the linear mesh geometry (no field data)."""
    import pyvista as pv

    from . import naming
    from .regions import format_region_table

    print(f"Reading mesh from {Path(re2file).name} ...", flush=True)
    mesh = read_re2_mesh(re2file)
    print(f"  {mesh.nelgt} elements, {mesh.bface_corners.shape[0]} boundary "
          f"faces, ndim={mesh.ndim}.", flush=True)
    if mesh.is_cht:
        print(f"  NOTE: conjugate-heat-transfer mesh ({mesh.nelgv} fluid + "
              f"{mesh.nelgt - mesh.nelgv} solid); only the fluid boundary "
              "faces stored in the .re2 are exported.", flush=True)

    group, infos, kind = _boundary_groups(mesh, normal_angle_deg)
    print(f"\nBoundary blocks (grouped by {kind}):")
    print(format_region_table(infos))

    cfg_path = Path(re2file).parent / f"{casename}_re2_names.json"
    names = naming.resolve_names(infos, cfg_path, casename,
                                 interactive=interactive, reconfigure=reconfigure)
    for info in infos:
        print(f"    block {info.region_id} ({kind} {info.code}) -> "
              f"{names[info.region_id]}")

    # Assemble the multiblock: volume + a "boundaries" group of named blocks.
    root = pv.MultiBlock()
    if write_volume:
        root["volume"] = _volume_grid(mesh)
    bnd = pv.MultiBlock()
    used = {}
    for info in infos:
        name = naming.sanitize(names[info.region_id])
        while name in used:  # guard against duplicate names
            name = f"{name}_{info.region_id}"
        used[name] = True
        bnd[name] = _boundary_polydata(mesh, group == info.region_id)
    root["boundaries"] = bnd

    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    vtm = outdir / f"{casename}_re2_mesh.vtm"
    root.save(str(vtm))
    print(f"\nWrote {vtm}", flush=True)
    print("Open it in ParaView — the pipeline shows 'volume' and each named "
          "boundary block (toggle/color per block; no thresholding needed).",
          flush=True)
